apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana-kombat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talana-kombat
  template:
    metadata:
      labels:
        app: talana-kombat
    spec:
      containers:
        - name: talana-kombat
          image: #Poner imagen aca
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: ENV
              value: prod
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: docker-hub-key
---
apiVersion: v1
kind: Service
metadata:
  name: talana-kombat
spec:
  type: NodePort
  selector:
    app: talana-kombat
  ports:
    - port: 3000
      targetPort: 8080
